services:
    wordpress:
        image: wordpress
        ports:
            - 8085:80
        depends_on:
            - mysql
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: sd23
        volumes:
            - ./wordpressvol:/var/www/html
        networks:
            searchwork:
                ipv4_address: "192.168.1.22"
    mysql:
        image: mysql:latest
        ports:
            - 3333:3306
        environment:
            MYSQL_DATABASE: sd23
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysqlvol:/var/lib/mysql
        networks:
            searchwork:
                ipv4_address: "192.168.1.23"
networks:
    searchwork:
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"